pw6_formation:
    resource:   "@PW6FormationBundle/Resources/config/routing.yml"
    prefix:     /formation

pw6_user:
    resource:   "@PW6UserBundle/Resources/config/routing.yml"
    prefix:     /user

app:
    resource:   "@AppBundle/Controller/"
    type:       annotation

login:
    path:       /login
    defaults:
        _controller: PW6UserBundle:Security:login

login_check:
    path:       /login_check

logout:
    path:       /logout

signin:
    path:       /signin
    defaults:
        _controller: PW6UserBundle:Security:signin
