forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

recrut:
    resource: "@RecrutBundle/Controller/"
    type:     annotation
    prefix:   /

stat:
    resource: "@StatBundle/Controller/"
    type:     annotation
    prefix:   /

formation:
    resource: "@FormationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
