# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    access_control:
        - {path: ^/formation, roles: ROLE_USER }
        - {path: ^/user/view/, roles: ROLE_USER }
        - {path: ^/user/admin/, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        PW6\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        bdd:
            entity:
                class: PW6\UserBundle\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:        ^/(_(profiler|wdt)|css|images|js)/
            security:       false

        main:
            pattern: ^/
            anonymous: true
            form_login: ~
            provider: bdd
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /
