PW6\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: PW6\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        fname:
            type: string
            length: 255
        pname:
            type: string
            length: 255
        password:
            type: string
            length: 255
        mail:
            type: string
            length: 255
        roles:
            type: array
    lifecycleCallbacks: {  }
