PW6\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: PW6\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        mail:
            type: string
            length: 255
            unique: true
        roles:
            type: array
        salt:
            type: string
            length: 255
    oneToOne:
        perso:
            targetEntity: Personnel
            joinColumn:
                name: perso_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
