pw6_recrutement_home:
    path:     /
    defaults:
        _controller: PW6RecrutementBundle:Recrutement:index

pw6_recrutement_view:
    path:     /advert/{id}
    defaults:
        _controller: PW6RecrutementBundle:Advert:view
    requirements:
        id:   \d+

pw6_recrutement_add:
    path:     /add
    defaults:
        _controller: PW6RecrutementBundle:Advert:add

pw6_recrutement_apply:
    path:     /apply/{id}
    defaults:
        _controller: PW6RecrutementBundle:Advert:apply
    requirements:
        id:   \d+

pw6_recrutement_edit:
    path:     /edit/{id}
    defaults:
        _controller: PW6RecrutementBundle:Advert:edit
    requirements:
        id:   \d+

pw6_recrutement_delete:
    path:     /delete/{id}
    defaults:
        _controller: PW6RecrutementBundle:Advert:delete
    requirements:
        id:   \d+

pw6_recrutement_gestionCandidat:
    path:     /gestionCandidat
    defaults:
        _controller: PW6RecrutementBundle:Recrutement:gestionCandidat
