pw6_formation_home:
    path:     /{page}
    defaults:
        _controller: PW6FormationBundle:Advert:index
        page:        1
    requirements:
        page: \d*

pw6_formation_view:
    path:     /advert/{id}
    defaults:
        _controller: PW6FormationBundle:Advert:view
    requirements:
        id:   \d+

pw6_formation_add:
    path:     /add
    defaults:
        _controller: PW6FormationBundle:Advert:add

pw6_formation_edit:
    path:     /edit/{id}
    defaults:
        _controller: PW6FormationBundle:Advert:edit
    requirements:
        id:   \d+

pw6_formation_delete:
    path:     /delete/{id}
    defaults:
        _controller: PW6FormationBundle:Advert:delete
    requirements:
        id:   \d+
