pw6_user_view:
    path:     /advert/{id}
    defaults:
        _controller: PW6UserBundle:User:view
    requirements:
        id:   \d+

pw6_user_edit:
    path:     /edit/{id}
    defaults:
        _controller: PW6UserBundle:User:edit
    requirements:
        id:   \d+

pw6_user_delete:
    path:     /delete/{id}
    defaults:
        _controller: PW6UserBundle:User:delete
    requirements:
        id:   \d+
