<?php

namespace PW6\UserBundle\Repository;

/**
 * PersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnelRepository extends \Doctrine\ORM\EntityRepository
{
}
